sudo: false

language: node_js

cache:
  directories: [~/.npm]

notifications:
  email: false

node_js:
  - lts/carbon

install:
  - travis_retry yarn install

script:
  - node --version
  - npm --version
  - yarn --version
  - yarn build:prod
