# The types that aigis will scan to document comment
source_type:
  - .scss

# The directory containing the source files to parse recursively
source:
  - ./src/

# The directory that aigis will build to
dest: ./build/styleguide

# The assets needed to build the docs
# You may put doc related assets here too: images, css, etc.
dependencies:
  - ./src/styleguide/aigis_assets

# The directory containing the tempalte files to generate pages
# It must contain 'layout.xxx' and 'index.xxx' (.ejs or .jade or .hbs)
template_dir: ./src/styleguide/
template_engine: jade

ejs:
  root: process.cwd() + "/src"
